    FROM node:alpine3.23

    WORKDIR /app

    COPY --chown=node:node package*.json ./

    RUN chown -R node:node /app

    USER node

    RUN --mount=type=cache,target=/app/.npm \
        npm set cache /app/.npm && npm install


    COPY --chown=node:node . .

    EXPOSE 3000

    CMD ["npm", "start"]