    FROM node:alpine3.23 AS build

    WORKDIR /app

    COPY package*.json ./

    RUN --mount=type=cache,target=/root/.npm \
        npm set cache /root/.npm && npm install

    COPY . .

    RUN npm run build

    FROM nginx:1.29.4-alpine

    COPY --from=build /app/build /usr/share/nginx/html

    RUN rm /etc/nginx/conf.d/default.conf

    COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

    EXPOSE 80

    CMD ["nginx", "-g", "daemon off;"]